version: '3'
services:
  rtcm3:
    restart: always
    image: jancelin/centipede:rtklib
    ports:
     - 2101:2101
    devices:
     - "/dev/tty*:/dev/tty*"
    privileged: true
    volumes:
     - /rtkbase/docker/root/basertk/ubx:/rtkbase/data
    env_file:
      - ./rtk.env
    networks:
      - rtk
    environment:
      - RUN=out_caster
  log:
    restart: always
    image: jancelin/centipede:rtklib
    devices:
      - "/dev/tty*:/dev/tty*"
    privileged: true
    volumes:
      - /rtkbase/docker/root/basertk/ubx:/rtkbase/data
    env_file:
      - ./rtk.env
    networks:
      - rtk
    environment:
      - RUN=out_file
  conv:
    restart: "no"
    image: jancelin/centipede:rtklib
    privileged: true
    volumes:
      - ./:/rtkbase
    env_file:
      - ./rtk.env
    networks:
      - rtk
    entrypoint: "./ubx/RINEX/convbin.sh"
  rcv:
    restart: "no"
    image: jancelin/centipede:rtklib
    privileged: true
    volumes:
      - /rtkbase/docker/root/basertk:/rtkbase
    env_file:
      - ./rtk.env
    networks:
      - rtk
    entrypoint: ""
  receiver:
    restart: "no"
    image: jancelin/centipede:receiver
    devices:
      - "/dev/tty*:/dev/tty*"
    privileged: true
    networks:
      - rtk

networks:
  rtk:




