version: '3'
services:
  rtcm3:
    restart: always
    image: jancelin/centipede:rtklib
    ports:
     - 2101:2101
    devices:
     - "/dev/tty*:/dev/tty*"
    privileged: true
    volumes:
     - /home/jancelin/rtkbase/docker/root/basertk/ubx:/rtkbase/data
    env_file:
      - ./rtk.env
    environment:
      - RUN=out_caster
  log:
    restart: always
    image: jancelin/centipede:rtklib
    devices:
      - "/dev/tty*:/dev/tty*"
    privileged: true
    volumes:
      - /home/jancelin/rtkbase/docker/root/basertk/ubx:/rtkbase/data
    env_file:
      - ./rtk.env
    environment:
      - RUN=out_file
  conv:
    restart: "no"
    image: jancelin/centipede:rtklib
    privileged: true
    volumes:
      - /home/jancelin/rtkbase/docker/root/basertk:/rtkbase
    env_file:
      - ./rtk.env
    entrypoint: "RINEX/convbin.sh"
  rcv:
    restart: "no"
    image: jancelin/centipede:rtklib
    privileged: true
    volumes:
      - /home/jancelin/rtkbase/docker/root/basertk:/rtkbase
    env_file:
      - ./rtk.env
    entrypoint: ""
