version: '3'
services:
  base:
    restart: always
    image: jancelin/rtkbase:caster-file
    ports:
     - 2101:2101
     - 2000:2000
    devices:
     - "/dev/tty*:/dev/tty*"
    privileged: true
    volumes:
     - /home/jancelin/rtkbase/docker/amd86-64/root/basertk/ubx:/rtkbase/data
    env_file:
      - ./rtk.env
    environment:
      - RUN=out_caster
  log:
    restart: always
    image: jancelin/rtkbase:caster-file
    devices:
      - "/dev/tty*:/dev/tty*"
    privileged: true
    volumes:
      - /home/jancelin/rtkbase/docker/amd86-64/root/basertk/ubx:/rtkbase/data
    env_file:
      - ./rtk.env
    environment:
      - RUN=out_file
