version: '3'
services:
  base:
    restart: always
    image: jancelin/rtkbase:caster-file
    ports:
     - 2101:2101
     - 2000:2000
    devices:
     - "/dev/tty*:/dev/tty*"
    privileged: true
    volumes:
     - ./ubx:/rtkbase/data
    env_file:
      - ./rtk.env


