version: '3'
services:
  base:
    restart: always
    image: jancelin/rtkbase:rtkbase
#    build:
#      context: https://github.com/jancelin/rtkbase.git#master:/docker/amd86-64
    ports:
     - 2101:2101
     - 2000:2000
    devices:
     - "/dev/tty*:/dev/tty*"
    privileged: true
#    volumes:
#     - logs:
    environment:
      - MNT_NAME=BASE
      - SRV_ADDR=caster.centipede.fr
      - SVR_PORT=2101
      - SVR_PWD=centipede
      - COM_PORT=ttyACM0
      - COM_PORT_SETTINGS='115200:8:n:1'
      - RECV_FORMAT=ubx
      - POSITION='45.99211717163 -1.02813790378 58.954'
      - RTCM_MSG='1006,1007,1008,1033,1077,1087,1097,1107,1117,1127,1019,1020,1042,1045,1046'
      - RECEVEIVER='Ublox_F9P'
      - TCP_PORT=2000
      - TCP_IP=192.168.43.93
#volumes:
#  logs:


#docker run  --rm --name rtk _p 2101:2101  -e MNT_NAME=BASE -e SRV_ADDR=caster.centipede.fr -e SRV_PORT=2101 -e COM_PORT=ttyACM0 -e POSITION='45.99211717163 -1.02813790378 58.954' -e RTCM_MSG='1006,1007,1008,1033,1077,1087,1097,1107,1117,1127,1019,1020,1042,1045,1046' --device=/dev/tty*:/dev/tty* --privileged jancelin/rtkbase:rtkbase_
