version: '3'
services:
  base:
    restart: always
    image: jancelin/rtkbase:rtkbase
#    build:
#      context: https://github.com/jancelin/rtkbase.git#master:/docker/amd86-64
    ports:
     - 2101:2101
     - 2000:2000
    devices:
     - "/dev/tty*:/dev/tty*"
    privileged: true
#    volumes:
#     - logs:
    env_file:
      - ./rtk.env

#volumes:
#  logs:


#docker run  --rm --name rtk -p 2101:2101  -e MNT_NAME=BASE -e SRV_ADDR=caster.centipede.fr -e SRV_PORT=2101 -e COM_PORT=ttyACM0 -e POSITION='45.999381 -1.213787 50' -e RTCM_MSG='1006,1007,1008,1033,1077,1087,1097,1107,1117,1127,1019,1020,1042,1045,1046' --device=/dev/tty*:/dev/tty* --privileged jancelin/rtkbase:rtkbase
