version: '3'
services:
  web:
    image: jancelin/centipede:cmd
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - ./:/mnt/fs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./cmd.env
    entrypoint: ["cloudcmd"]

